import { Game } from "@/constants/game.type";

const game: Game = {
  id: 1,
  name: "test",
  pic: "/assets/home/testHero.svg",
  introduction: "test test test test test tst teste test test tests",
  characterIcon: "/assets/home/lock.svg",
  characterName: "test",
  abilities: [
    {
      name: "test",
      icon: "/assets/home/test_factor.svg",
      information: "test test test test",
      coolDown: "160 Seconds",
      max: "1",
    },
    {
      name: "test",
      icon: "/assets/home/test_factor.svg",
      information: "test test test test",
      coolDown: "160 Seconds",
      max: "1",
    },
    {
      name: "test",
      icon: "/assets/home/test_factor.svg",
      information: "test test test test",
      coolDown: "160 Seconds",
      max: "1",
    },
  ],
  skills: [
    {
      name: "tes test",
      information: "test test test test test",
      unlock: "Level 4",
      max: "11",
    },
    {
      name: "tes test",
      information: "test test test test test",
      unlock: "Level 4",
      max: "11",
    },
    {
      name: "tes test",
      information: "test test test test test",
      unlock: "Level 4",
      max: "11",
    },
    {
      name: "tes test",
      information: "test test test test test",
      unlock: "Level 4",
      max: "11",
    },
    {
      name: "tes test",
      information: "test test test test test",
      unlock: "Level 4",
      max: "11",
    },
  ],
  items: [
    {
      name: "test test",
      icon: "/assets/home/test_factor.svg",
      bonus: ["aa", "bb"],
      normal: ["aa", "bb"],
      scarce: ["bbb", "c1122"],
      rare: ["a", "b"],
      epic: ["aa", "b"],
      legendary: ["aac", "1b"],
      mythical: ["ac", "1d"],
    },
    {
      name: "test test",
      icon: "/assets/home/test_factor.svg",
      bonus: ["aa", "bb"],
      normal: ["aa", "bb"],
      scarce: ["bbb", "c1122"],
      rare: ["a", "b"],
      epic: ["aa", "b"],
      legendary: ["aac", "1b"],
      mythical: ["ac", "1d"],
    },
    {
      name: "test test",
      icon: "/assets/home/test_factor.svg",
      bonus: ["aa", "bb"],
      normal: ["aa", "bb"],
      scarce: ["bbb", "c1122"],
      rare: ["a", "b"],
      epic: ["aa", "b"],
      legendary: ["aac", "1b"],
      mythical: ["ac", "1d"],
    },
    {
      name: "test test",
      icon: "/assets/home/test_factor.svg",
      bonus: ["aa", "bb"],
      normal: ["aa", "bb"],
      scarce: ["bbb", "c1122"],
      rare: ["a", "b"],
      epic: ["aa", "b"],
      legendary: ["aac", "1b"],
      mythical: ["ac", "1d"],
    },
    {
      name: "test test",
      icon: "/assets/home/test_factor.svg",
      bonus: ["aa", "bb"],
      normal: ["aa", "bb"],
      scarce: ["bbb", "c1122"],
      rare: ["a", "b"],
      epic: ["aa", "b"],
      legendary: ["aac", "1b"],
      mythical: ["ac", "1d"],
    },
    {
      name: "test test",
      icon: "/assets/home/test_factor.svg",
      bonus: ["aa", "bb"],
      normal: ["aa", "bb"],
      scarce: ["bbb", "c1122"],
      rare: ["a", "b"],
      epic: ["aa", "b"],
      legendary: ["aac", "1b"],
      mythical: ["ac", "1d"],
    },
  ],
  outfits: [
    {
      name: "test test ",
      pic: "/assets/home/testHero.svg",
      requirements: "testesresfjds fdskjfjdslk jfkdsj ljfkdsj",
    },
    {
      name: "test test ",
      pic: "/assets/home/testHero.svg",
      requirements: "testesresfjds fdskjfjdslk jfkdsj ljfkdsj",
    },
    {
      name: "test test ",
      pic: "/assets/home/testHero.svg",
      requirements: "testesresfjds fdskjfjdslk jfkdsj ljfkdsj",
    },
    {
      name: "test test ",
      pic: "/assets/home/testHero.svg",
      requirements: "testesresfjds fdskjfjdslk jfkdsj ljfkdsj",
    },
    {
      name: "test test ",
      pic: "/assets/home/testHero.svg",
      requirements: "testesresfjds fdskjfjdslk jfkdsj ljfkdsj",
    },
  ],
};

export default function handler(req: any, res: any) {
  res.status(200).json({ message: "success", code: 0, data: game });
}
